service: brickly-serverless

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  stage: ${opt:stage}
  iam:
    role: ${env:IAM_ROLE_ARN}

custom:
  serverless-offline:
    noPrependStageInUrl: true
  environment:
    DB_HOST:
      dev: "dev_host"
    DB_USER:
      dev: "dev_user"
    DB_PASSWORD:
      dev: "dev_password"
    DB_NAME:
      dev: "dev_name"
  pythonRequirements:
    dockerizePip: true

functions:
  app:
    handler: main.handler
    url: true
    events:
      - http:
          method: ANY
          path: /{proxy+}

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!env/**'
    - '!package.json'
    - '!package-lock.json'
    - '!requirements.txt'