service: brickly-serverless

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  stage: ${opt:stage}
  environment:
    ENVIRONMENT: ${opt:stage}
    DB_HOST: ${self:custom.environment.DB_HOST.${self:provider.stage}}
    DB_USER: ${self:custom.environment.DB_USER.${self:provider.stage}}
    DB_PASSWORD: ${self:custom.environment.DB_PASSWORD.${self:provider.stage}}
    DB_NAME: ${self:custom.environment.DB_NAME.${self:provider.stage}}
  iam:
    role: ${env:IAM_ROLE_ARN}

custom:
  serverless-offline:
    noPrependStageInUrl: true
  environment:
    DB_HOST:
      dev: "brickly-database-dev.cv7vbjo3n63b.ap-south-1.rds.amazonaws.com"
    DB_USER:
      dev: "brickly_admin"
    DB_PASSWORD:
      dev: ${env:DATABASE_PWD}
    DB_NAME:
      dev: "brickly_database_dev"
  pythonRequirements:
    dockerizePip: true

functions:
  app:
    handler: main.handler
    url: true
    events:
      - http:
          method: ANY
          path: /{proxy+}

plugins:
  - serverless-offline
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!env/**'
    - '!package.json'
    - '!package-lock.json'
    - '!requirements.txt'
    - '!.serverless/**'