"""Make certain fields in user and house model mandatory

Revision ID: 59e8dadd372a
Revises: 85e75fa9f7cf
Create Date: 2022-12-18 00:56:01.611081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59e8dadd372a'
down_revision = '85e75fa9f7cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('house', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('house', 'location',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('house', 'city',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('house', 'value',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('house', 'funded',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user', 'phone_number',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'cnic_number',
               existing_type=mysql.VARCHAR(length=13),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'cnic_number',
               existing_type=mysql.VARCHAR(length=13),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('house', 'funded',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('house', 'value',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('house', 'city',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('house', 'location',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('house', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
