"""Create a sale table

Revision ID: 7f3e090a32eb
Revises: 929aa3629b82
Create Date: 2022-12-18 23:39:40.377359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f3e090a32eb'
down_revision = '929aa3629b82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('sale_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_id'), 'sale', ['id'], unique=False)
    op.create_table('user_house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('invested_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_house_id'), 'user_house', ['id'], unique=False)
    op.drop_table('user_house_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_house_association',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('house_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invested_amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], name='user_house_association_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_house_association_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_user_house_id'), table_name='user_house')
    op.drop_table('user_house')
    op.drop_index(op.f('ix_sale_id'), table_name='sale')
    op.drop_table('sale')
    # ### end Alembic commands ###
