"""Add role property in user table

Revision ID: 85e75fa9f7cf
Revises: e4fe185b0df4
Create Date: 2022-12-17 21:29:49.517878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e75fa9f7cf'
down_revision = 'e4fe185b0df4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('user', 'estate_agent', name='roles'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
