"""Use class based for association instead of Table function from sqlalchemy

Revision ID: 929aa3629b82
Revises: 59e8dadd372a
Create Date: 2022-12-18 20:36:47.958216

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '929aa3629b82'
down_revision = '59e8dadd372a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_house_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('invested_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_house_association')
    # ### end Alembic commands ###
