"""Property to find if user is blocked or not

Revision ID: e4fe185b0df4
Revises: 08ffb7751329
Create Date: 2022-12-17 17:40:05.230197

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e4fe185b0df4"
down_revision = "08ffb7751329"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("blocked", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "blocked")
    # ### end Alembic commands ###
